- docs/shinylive.qmd
This adds a note to the shinylive page about Quarto Shiny dashboards.
> Update shinylive page with note about quarto shiny dashboards

- components/outputs/plot-seaborn.qmd
this is the seaborn version for #16
> Component: output plot seaborn

- components/outputs/plot-plotly.qmd
It doesn't seem there is a website for shinywidgets yet?
So the relevant functions section is currently linking to the function signature in the actual codebase.
> Component: output plot plotly

- docs/install.qmd
Fix minor typos in venv installation instructions.
> Fix typos in venv installation instructions in install.qmd

- quarto-style.scss
This updates to Shiny 0.6.1 for the API docs.
> Update to Shiny 0.6.1 for API docs

- components/inputs/action-button.qmd
- components/inputs/action-link.qmd
Fixes the shinylive preview apps for the action button and action link
> fix(components): shinylive link for action button and link

- components/_partials/components.css
- include-in-header.html
- layouts/_partials/layouts.css
There are no actual changes here, just formatting applied by VS Code
> Format some CSS and HTML files

- docs/shinylive.qmd
- requirements.txt
This PR is related to https://github.com/posit-dev/py-shiny/issues/1092#issuecomment-1919868273.
> Add information about Shinylive Pyodide version

- docs/jupyter-widgets.qmd
Correct the URL for Altair project.
> Update Altair Website

- docs/ui-customize.qmd
- requirements.txt
> Document static files in Express

- docs/module-communication.qmd
This cleans up some of the code for module examples.
> Clean up module example code

- docs/deploy-cloud.qmd
- docs/deploy-on-prem.qmd
https://github.com/rstudio/rsconnect-python/blob/master/CHANGELOG.md#1220---2024-01-23
> docs: Document required version of rsconnect-python for Shiny Express

- images/clipboard.svg
- index.css
- index.qmd
- quarto-style.scss
This updates the home page copy to guide the user towards installing Shiny
> New home page

- docs/helpers.py
Follow up to #159 (in support of https://github.com/rstudio/shiny-dev-center/pull/341)
> Auto-detect language in `append_shinylive_chunk()`

- docs/overview.qmd
Closes https://github.com/posit-dev/py-shiny/issues/1533
> Fix link to shinylive examples

- docs/module-communication.qmd
duplicated import for 'module'
> chore(app): Remove duplicate import statement

- _extensions/quarto-ext/shinylive/_extension.yml
- _extensions/quarto-ext/shinylive/shinylive.lua
- docs/jupyter-widgets.qmd
- docs/overview.qmd
Attempts to fix this problem on https://shiny.posit.co/py/docs/overview.html
> Fix altair examples by gutting soft_dependency hack

- docs/comp-r-shiny.qmd
I've removed the output decorator from the comparison page, please take a look at it.
> Removed the output decorator from the comparison page 

- requirements.txt
Update to the shiny v1.2.0 release
Also, prunes seemingly unneeded dependencies added in #24 and #31
> v1.2.0 release candidate

- docs/install-create-run.qmd
> docs: Alias `install.html` for `install-create-run.html`

- docs/deploy-cloud.qmd
As discussed with @wch. I also removed some text for shinyapps.io to position Connect Cloud as the next-gen tool.
> add Connect Cloud as deployment option

- docs/end-to-end-testing.qmd
This pull request includes significant updates to the `docs/end-to-end-testing.qmd` file to enhance the clarity and comprehensiveness of the end-to-end testing documentation for Shiny apps. The changes include restructuring the content, providing detailed explanations, and adding step-by-step guides for creating and testing a Shiny app with Playwright.
Improvements to documentation:
* Updated the title to "End-to-End Testing Your App" for better clarity.
* Expanded the introduction to explain the importance and benefits of end-to-end testing in a more engaging manner.
* Introduced Playwright and its advantages for Shiny app testing, highlighting its features like cross-browser testing and dynamic wait times.
Step-by-step guides:
* Added a detailed guide on creating a simple Shiny app and …
> docs(testing): Update end-to-end-testing.qmd

- components/index.qmd
- layouts/index.qmd
Introduced by #251 
See https://pr-251--pyshiny.netlify.app/components 
vs https://pr-254--pyshiny.netlify.app/components
> Fix broken components/layout banner layout

- get-started/include/why-virtual-env.qmd
testing to see if this will fix the last warning in #292
> try using an absolute path for the include file

- docs/genai-chatbots.qmd
This pull request fixes import syntax errors in the `docs/genai-chatbots.qmd` file to ensure proper functionality and consistency in the examples provided.
> fix(docs): Fix imports

- docs/genai-chatbots.qmd
This pull request removes unnecessary code related to resetting user input in the `docs/genai-chatbots.qmd` file. The change simplifies the chatbot's behavior by eliminating an unused `@reactive.effect` function.
> fix(docs): remove code causing app to not load

- docs/genai-chatbots.qmd
- docs/genai-inspiration.qmd
- docs/genai-rag.qmd
- docs/genai-structured-data.qmd
- docs/genai-tools.qmd
This pull request includes minor corrections to grammar and word usage in the documentation to improve clarity and readability.
> fix(docs): Fix typos

- get-started/install.qmd
> Removed one 'for' at line 175 in install.qmd
