posit-dev/py-shiny-site

- components/display-messages/help-text.qmd
fixes this error:
```
% make serve
. venv/bin/activate && quarto preview
ERROR: YAMLError: /Users/danielchen/git/rstudio/py-shiny-site/components/display-messages/help-text.qmd:
missed comma between flow collection entries at line 45, column 2:
[`ui.help_text()`](TODO ADD LINK  ... 
^
Stack trace:
missed comma between flow collection entries at line 45, column 2:
[`ui.help_text()`](TODO ADD LINK  ... 
^
at generateError (file:///Applications/quarto/bin/quarto.js:10497:12)
at throwError (file:///Applications/quarto/bin/quarto.js:10500:11)
at readFlowCollection (file:///Applications/quarto/bin/quarto.js:10883:20)
at composeNode (file:///Applications/quarto/bin/quarto.js:11316:137)
at readBlockMapping (file:///Applications/quarto/bin/quarto.js:11096:20)
at composeNode …
```
> fix indendation for render

- docs/outputs.qmd
This example is currently broken (I'm pretty sure because a recent ipyleaflet release removed the Stamen basemaps)
> Avoid Stamen basemaps in ipyleaflet example

- requirements.txt
This PR updates shinylive to 0.1.3, which includes Shiny 0.6.1. This allows the use of Shiny Express in code blocks.
> Update to shinylive 0.1.3

- components/_partials/components.css
- include-in-header.html
- quarto-style.scss
@gadenbuie thanks so much for this.  
I'm wondering if we could use Bootstrap's "[dismiss on next click](https://getbootstrap.com/docs/5.3/components/popovers/#dismiss-on-next-click)" option for the popovers?
> tooltip styling and express/core tab accentuation

- components/_partials/components.css
- docs/comp-r-shiny.qmd
- docs/custom-component-one-off.qmd
- docs/custom-components-pkg.qmd
- docs/express-to-core.qmd
- docs/express-vs-core.qmd
- docs/install-create-run.qmd
- docs/jupyter-widgets.qmd
- docs/overview.qmd
- docs/reactive-patterns.qmd
- docs/ui-overview.qmd
- include-in-header.html
- layouts/_partials/layouts.css
- quarto-style.scss
The main purpose of this PR is to allow `.shiny-mode-tabset` to be used more generally throughout the site (and look better without hacks on https://shiny.posit.co/py/docs/ui-overview.html) 
While I was there, I discovered we have a lot of overlapping tabset styling logic, scattered in 3 different places. This PR removes that redundancy and also leans on `.nav-underline` to provide (most of) the underline styling.
> Refactor/consolidate tabset styling, use shiny-mode-tabset more generally

- include-in-header.html
Fixes #104
We needed to insert the shinylive link button _after_ the code copy button, I think that quarto's javascript logic finds the copy button's previous sibling to find the code to copy.
> fix: Insert shinylive button without breaking code copy btn

- components/_partials/components-list.ejs
- components/_partials/components.css
- components/display-messages/modal/index.qmd
- components/display-messages/notifications/index.qmd
- components/display-messages/tooltips/index.qmd
- components/index.qmd
- components/inputs/select-multiple/index.qmd
- components/inputs/select-single/index.qmd
- components/inputs/selectize-multiple/index.qmd
- components/inputs/selectize-single/index.qmd
- components/outputs/data-grid/index.qmd
- components/outputs/datatable/index.qmd
- components/outputs/map-ipyleaflet/index.qmd
- components/outputs/plot-matplotlib/index.qmd
- components/outputs/plot-seaborn/index.qmd
- components/outputs/text/index.qmd
- components/outputs/ui/index.qmd
- components/outputs/value-box/index.qmd
- components/outputs/verbatim-text/index.qmd
- layouts/_partials/layouts.css
- layouts/arrange/index.qmd
- layouts/index.qmd
- layouts/navbars/index.qmd
- layouts/panels-cards/index.qmd
- layouts/sidebars/index.qmd
- layouts/tabs/index.qmd
Restores the missing **Variations** heading in the components gallery.
Also switches to using CSS to add the section dividers and spacing via `border-top` on `h2` elements, except the first `h2` on the page. This works for both `components/` and `layouts/`.
I also made sure that sections in `components/` that are below `## Details` are level-3 headings (e.g. `### Another detail`) so they fit in the Details section.
While looking at the headings, I noticed that there were just heading jumps (e.g. an `<h5>` nested inside an `<h2>`). I updated the heading structure to use `h1` through `h3`. Most of the `<h5>` elements were used for styling, so I switched these out for `<div class="h5">` to get the same affect without putting the element in the accessibility tree.
While looking at that (using …
> Fix components gallery missing Variations heading

- docs/user-interfaces.qmd
At least with the old code, you get a warning from Pandas (when running locally on pandas 2.2.1) about mutating a view, which is how I noticed this.
> Copy Pandas dataframe before mutating

- components/display-messages/modal/index.qmd
- components/display-messages/notifications/app-preview.py
- components/display-messages/notifications/app-variation-replace-update-a-notification-core.py
- components/display-messages/notifications/app-variation-track-and-remove-notifications-core.py
- components/display-messages/notifications/app-variation-track-and-remove-notifications-express.py
- components/display-messages/notifications/index.qmd
- components/inputs/action-button/app-detail-preview.py
- docs/apps/comp-streamlit/penguins/app-core.py
- docs/apps/comp-streamlit/penguins/app-express.py
This PR updates examples to use lower-case  `reactive.calc`, `.effect`, and `.value`.
> Use lower-case `reactive.calc`, `.effect`, and `.value`

- requirements.txt
This updates to shinylive 0.2.4, so that it will have Shiny 0.8.1 in shinylive.
> Update to shinylive 0.2.4

- templates/_partials/template-listing.ejs
Removes the `target="_blank"` so that links to a template in the template gallery don't open in a new browser tab.
> Open template link in same browser tab

- components/outputs/data-grid/app-variation-select-rows-core.py
- components/outputs/data-grid/app-variation-select-rows-express.py
- components/outputs/data-grid/index.qmd
- components/outputs/datatable/app-variation-select-rows-core.py
- components/outputs/datatable/app-variation-select-rows-express.py
- components/outputs/datatable/index.qmd
This fixes documentation and examples on doing row selections, for Shiny 0.9.0.
> Update data grid/table row selection docs

- requirements.txt
This PR updates py-shiny to 0.10.1 for API docs, and py-shinylive to 0.4.0.
> Update py-shiny and py-shinylive

- docs/reactive-mutable.qmd
Updates the problem/solution examples in the `reative-mutable` article.
1. I put the problem/solution examples in callouts so that it's visually clear which one provides the pattern to follow.
2. Small edit to make it easier to see the problem with the leaky changes example
3. Use `@render.code` instead of `@render.text` and change "raw values" to "user values" to make it easier to read.
4. Added a section on python operations that create copies.
Preview: https://pr-151--pyshiny.netlify.app/docs/reactive-mutable.html
> reactive-mutable: tweak problem/solution examples

- docs/custom-components-pkg.qmd
- docs/install-create-run.qmd
Updates the link to the `Posit.shiny` VS Code extension. See https://shiny.posit.co/blog/posts/shiny-vscode-1.0.0/ for more details.
> Update shiny-vscode link

- components/make-static-previews.py
This PR gets rid of the spinners in the input section of https://shiny.posit.co/py/components/ that never go away
https://github.com/posit-dev/py-shiny-site/assets/1365941/857b3c58-516c-4825-b8e7-920e3e2bfcdb
> Disable busy indication in static previews

- _quarto.yml
This has two effects: making the build faster, as quarto render currently uses a slow Lua JSON parser to deserialize objects.json on every page render; and generating an objects.txt file, which can be used by sphinx so that downstream projects can interlink with us.
> Enable fast mode

- _quarto.yml
- docs/deploy-on-prem.qmd
- docs/deploy.qmd
This is to provide a single URL that we can point at for people to learn about our deployment options.
From @EconomiCurtis:
> tl:dr, we can please have one URL for https://shiny.posit.co/py/deploy advice?
> 
> One thing that comes up frequently in the community where I feel I need to reply is people asking about how to deploy a shiny app. Sometimes they'll explain their goals and I can recommend shinylive, Connect, [Shinyapps.io](http://shinyapps.io/), or something else. But often they leave that context out and I have to say "it depends" and here's several articles that might work for you. (Cloud Hosting, Self-hosted, shinylive), and point to https://shiny.posit.co/py/
> 
> I think it's be great to have one URL to "Deployment" (https://shiny.posit.co/py/deploy ) that helps people …
> Add deployment overview doc

- docs/user-interfaces.qmd
> #155 Update id reference

- docs/helpers.py
… so that shiny-dev-center can use it
> Abstract out `express_core_preview()` internals into a `app_preview_code()` helper

- _quarto.yml
- components/_metadata.yml
- gallery/_metadata.yml
- index.qmd
- layouts/_metadata.yml
- templates/_metadata.yml
Adds repo actions to articles, reference pages, etc.
Repo actions can be disabled on pages or in subdirectories by adding `repo-actions: false` to the page frontmatter or to `_metadata.yml` in a directory.
[More information in Quarto's docs](https://quarto.org/docs/websites/website-navigation.html#github-links).
> feat: Enable repo-actions

- docs/comp-r-shiny.qmd
there are two 'observeEvent" entries. I think one should be enough right? Any reason to keep both?
> fix: Correct the duplicate R function name

- docs/jupyter-widgets.qmd
- docs/overview.qmd
- requirements.txt
Should no longer be needed after https://github.com/posit-dev/py-shinylive/pull/36
> Test whether we can remove altair soft_dependencies hack

- Makefile
Fixes https://github.com/posit-dev/py-shiny-site/issues/181
Fixes https://github.com/posit-dev/py-shiny-site/issues/191
Fixes https://github.com/posit-dev/py-shiny/issues/1568
This addresses py-shiny-site installing into `venv` which was causing the example supporting files to be removed.
> bug(py-shiny): Fix examples missing supporting files

- .github/workflows/deploy-docs.yml
We have a `Run quarto-dev/quarto-actions/setup@v2` step with the version specified. However, the `r-lib/actions/setup-r-dependencies@v2` step in the workflow was indirectly causing another copy of `Run quarto-dev/quarto-actions/setup@v2` to run, but without a version specified. This installation failed because the system doesn't want to downgrade the .deb package.
https://github.com/posit-dev/py-shiny-site/actions/runs/10250692524/job/28356982088#step:9:2457
> Install quarto before installing R dependencies

- docs/jupyter-widgets.qmd
- docs/overview.qmd
The pydeck v0.9 has (hopefully temporarily) removed it's ipywidgets support (https://github.com/visgl/deck.gl/pull/8854). 
Long term, we may want to consider bundling v0.8.0 with shinylive (especially if they don't ever bring ipywidgets support back), but this is a more immediate fix for pydeck examples in the docs
> Pin pydeck to 0.8.0

- requirements.txt
Works around griffe v1.0.0 changes using same approach as https://github.com/posit-dev/py-shiny/pull/1627
Watch https://github.com/posit-dev/py-shiny/pull/1636 for Shiny using quartodoc 0.7.6
> temp: work around griffe v1.0.0 changes

- templates/basic-sidebar/index.qmd
From "Reactive plot in a sidebar" (sounds like the plot shows up in a sidebar) to "Reactive plot **with a** sidebar".
> fix: retitle basic-sidebar template

- Makefile
Seen in https://github.com/posit-dev/py-shiny-site/actions/runs/11245305450/job/31265057161?pr=221#step:9:765 from https://github.com/posit-dev/py-shiny-site/pull/221
> bug: Checkout full py-shiny repo when initing submodules

- requirements.txt
This fixes an incorrect package. In #31, the package in requirements.txt was added as `favicons`, but it should be `faicons`.
> Fix incorrect package

- docs/express-or-core.qmd
- docs/user-interfaces.qmd
Recent versions of ridgeplot started [requiring `statsmodels!=0.14.2`](https://github.com/tpvasconcelos/ridgeplot/commit/568caa3d72aac3a18ee6ceb8f32de112b2bf8454#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R44), which is exactly the version that currently gets [bundled with pyodide](https://pyodide.org/en/stable/usage/packages-in-pyodide.html). 
So, as workaround, we just pin the version for shinylive to version of ridgeplot just before that requirement was added (and the examples work fine)
> Pin ridgeplot to 0.1.25

- quarto-style.scss
- templates/survey-wizard/index.qmd
- templates/survey/index.qmd
Improve the link from our docs to shiny_validate, as pointed out by #238
- Use phrase "input validation" when describing shiny_validate
- Link directly to shiny_validate
> Improve reference to shiny_validate

- _quarto.yml
- quarto-style.scss
> Improved sidebar styling for 'Learn Shiny'

- docs/debug.qmd
- gallery/gallery.yml
Removing the `?_gl*` parts to links.
> chore: remove ?_gl* in URLs

- index.qmd
- quarto-style.scss
Updates the hero text on the front page to use Bootstraps `.display-1` for `font-size` and `line-height`, resulting in better display at all screen sizes.
This also untangles the `.gradient-text` class from font size and weight considerations.
> fix: Hero text

- get-started/index.qmd
- get-started/install.qmd
Somehow I had 2 commits that didn't make it into #261 so I cherry-picked them from my local branch.
Removes the bullet links in the install page and adds 2 more links to break up the text in the index
> Add and fix links to get started

- get-started/gallery-highlight.yml
images in the production site for the gallery and templates are 404-ing
working locally with the reference to use `../gallery` instead of `/gallery`
> bug(images): use relative links to reference gallery images, breaking prod site

- components/_partials/components.css
- get-started/index.qmd
- get-started/what-is-shiny.qmd
Perhaps we should do this more generally too since the components pages suffer from the same problem.
And also seems like shinylive should be doing this automatically?
> Don't show a flash of shinylive source code

- docs/comp-r-shiny.qmd
- docs/jupyter-widgets.qmd
- docs/overview.qmd
- docs/routing.qmd
- docs/user-interfaces.qmd
- get-started/create-run.qmd
- get-started/include/why-virtual-env.qmd
- templates/stock-app/index.qmd
fixes the links mentioned in #291 and #290.
~~The `get-started/include/deploy.qmd` issue seems to be okay? since it's mainly used as an include so the reference directory is the /get-started/install.qmd directory~~
> chore(URLs): fix link changes from #291

- docs/genai-chatbots.qmd
This pull request updates a documentation link in the `docs/genai-chatbots.qmd` file to point to the correct section of the Shiny documentation.
> fix(docs): use correct link to run the app
